# Generated by Django 6.0.3 on 2026-03-08 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_number', models.PositiveIntegerField(unique=True)),
                ('year', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-volume_number'],
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_number', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='journal.volume')),
            ],
            options={
                'ordering': ['-volume__volume_number', '-issue_number'],
                'unique_together': {('volume', 'issue_number')},
            },
        ),
        migrations.CreateModel(
            name='PaperIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_start', models.PositiveIntegerField(blank=True, null=True)),
                ('page_end', models.PositiveIntegerField(blank=True, null=True)),
                ('order_in_issue', models.PositiveIntegerField(default=1)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_assignments', to='journal.issue')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_assignments', to='papers.paper')),
            ],
            options={
                'ordering': ['order_in_issue'],
                'unique_together': {('paper', 'issue')},
            },
        ),
    ]
