# Generated by Django 6.0.3 on 2026-03-08 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('papers', '0002_alter_paper_status_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doi_generated', models.BooleanField(default=False)),
                ('pdf_formatted', models.BooleanField(default=False)),
                ('plagiarism_cleared', models.BooleanField(default=False)),
                ('published_in_volume', models.CharField(blank=True, max_length=50)),
                ('published_in_issue', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='publication_record', to='papers.paper')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
