# Generated by Django 6.0.3 on 2026-03-08 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('abstract', models.TextField()),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated keywords', max_length=500)),
                ('corresponding_email', models.EmailField(max_length=254)),
                ('pdf_file', models.FileField(blank=True, upload_to='papers/pdfs/%Y/%m/')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('revision_requested', 'Revision Requested'), ('revised', 'Revised'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('published', 'Published')], default='submitted', max_length=20)),
                ('doi', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='DOI')),
                ('citation_text', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='papers', to='papers.category')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_papers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaperAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=255)),
                ('affiliation', models.CharField(blank=True, max_length=500)),
                ('author_order', models.PositiveIntegerField(default=1)),
                ('is_corresponding', models.BooleanField(default=False)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='papers.paper')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_papers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['author_order'],
                'unique_together': {('paper', 'author_order')},
            },
        ),
    ]
