# Generated by Django 6.0.3 on 2026-03-08 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('papers', '0002_alter_paper_status_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlagiarismReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField(default=0.0, help_text='Overall similarity percentage 0-100')),
                ('is_flagged', models.BooleanField(default=False, help_text='True if similarity > threshold')),
                ('report_data', models.JSONField(blank=True, default=dict, help_text='Detailed match data')),
                ('checked_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plagiarism_report', to='papers.paper')),
            ],
        ),
    ]
